[online]
; 1 = force the game to run offline
; 0 = allow online functionality (not recommended with mods)
forceOffline=1

[savefile]
; 1 = use an alternative save file to avoid overwriting your main save
; 0 = use default save file (sl2)
useAlternativeSaveFile=1
; Set the extension for the alternative save file
; Allows you to have multiple alternative save files
alternativeSaveFileExtension="sl3"

[files]
; 1 = enable loading mods from a custom folder
useModOverrideDirectory=1
; Folder where mod files (assets) are located
modOverrideDirectory="./mods"

; 1 = enable loading extra DLL mods
useExtraDLLsDirectory=1
; Folder where extra DLL mods are located
extraDllsDirectory="./dllMods"

[qol]
; Skip the intro credits when starting the game
skipIntro=1